SCREEN_WIDTH = 80
SCREEN_HEIGHT = 25
MAP_HEIGHT = 22
MAP_WIDTH = 80
FLOOR = '.'
VOID = ' '
DOOR = '╬'
CORRIDOR = '░'
HORIZONTAL_WALL = '═'
VERTICAL_WALL = '║'
LEFT_TOP_WALL = '╔'
RIGHT_TOP_WALL = '╗'
LEFT_BOTTOM_WALL = '╚'
RIGHT_BOTTOM_WALL = '╝'
WALLS = {
    HORIZONTAL_WALL,
    VERTICAL_WALL,
    LEFT_TOP_WALL,
    RIGHT_TOP_WALL,
    LEFT_BOTTOM_WALL,
    RIGHT_BOTTOM_WALL,
    VOID,
}
ORC = "O"
MOVES = {
    'w': (0, -1),
    'a': (-1, 0),
    's': (0, 1),
    'd': (1, 0)
}