FLOOR = '.'
VOID = ' '
DOOR = '╬'
CORRIDOR = '░'
HORIZONTAL_WALL = '═'
VERTICAL_WALL = '║'
LEFT_TOP_WALL = '╔'
RIGHT_TOP_WALL = '╗'
LEFT_BOTTOM_WALL = '╚'
RIGHT_BOTTOM_WALL = '╝'

WALLS = {
    HORIZONTAL_WALL,
    VERTICAL_WALL,
    LEFT_TOP_WALL,
    RIGHT_TOP_WALL,
    LEFT_BOTTOM_WALL,
    RIGHT_BOTTOM_WALL,
    VOID,
}

COLOR_RESET = '\033[0m'
COLOR_GREEN = '\033[1;32m'
COLOR_BROWN = '\033[1;38;5;130m'
COLOR_YELLOW = "\033[1;38;5;226m"

COLOR_TABLE = {
    FLOOR: COLOR_GREEN + FLOOR + COLOR_RESET,
    DOOR: COLOR_BROWN + DOOR + COLOR_RESET,
    HORIZONTAL_WALL: COLOR_BROWN + HORIZONTAL_WALL + COLOR_RESET,
    VERTICAL_WALL: COLOR_BROWN + VERTICAL_WALL + COLOR_RESET,
    LEFT_TOP_WALL: COLOR_BROWN + LEFT_TOP_WALL + COLOR_RESET,
    RIGHT_TOP_WALL: COLOR_BROWN + RIGHT_TOP_WALL + COLOR_RESET,
    LEFT_BOTTOM_WALL: COLOR_BROWN + LEFT_BOTTOM_WALL + COLOR_RESET,
    RIGHT_BOTTOM_WALL: COLOR_BROWN + RIGHT_BOTTOM_WALL + COLOR_RESET
}